name: Build Latex Document


on:
  push:
    branches: 
      - gb

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: demo job
      run: echo hello world
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
          root_file: resume.tex

    
        
