name: LatexCompile


on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: demo job
      run: echo hello world
    
        
